---
title: Wethod Support
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
name: Wethod Help
baseurl: "/"
permalink: "/:title"
gems:
- jekyll-assets
- jekyll-last-modified-at
exclude:
- vendor
- Gemfile
- Gemfile.lock
- Rakefile
- readme.md
canonical_domain: http://support.wethod.com
assets:
  js_compressor: uglifier
  css_compressor: sass
